### ISSUE TITLE
Invert colors on `about:*` and chrome pages

### ISSUE THREAD

**Issue by taiite** [Max-Github/FireFoxInvertColors#12]
Colors are not inverted on `about:*` and chrome pages.

The most important one surely is `about:blank`, which is opened on new tabs (and maybe even on startup, depending on the browser settings). It would be great if it's possible to make it black.

**Comment by Max-Github** [comment]
I do not think this is possible.

From:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/insertCSS

>You can only inject CSS into pages whose URL can be expressed using a match pattern: meaning, its scheme must be one of "http", "https", "file", "ftp". This means that you can't inject CSS into any of the browser's built-in pages, such as about:debugging, about:addons, or the page that opens when you open a new empty tab.

**Comment by taiite** [comment]
I'm not really up to date with the new webextensions, but I understand the API is not as complete as the previous one. Maybe it'll get better in the future... :(

Meanwhile I've found a quick hack to have the `about:blank` pages black: https://superuser.com/questions/603218/how-to-make-the-aboutblank-page-black-or-any-other-color-in-firefox. It may be of use to someone passing by here. :)

**Comment by Max-Github** [comment]
The new API is getting better over time.
