### ISSUE TITLE
Option to exclude images

### ISSUE THREAD

**Issue by mdcclxv** [Max-Github/FireFoxInvertColors#14]
Just discovered this plugin and it's pretty useful, but inverting images it's a no go for me. A checkbox in the addon's options to exclude images would be really nice.

**Comment by Max-Github** [comment]
You are welcome to add a PR to include this feature.

We would either need to have different CSS files (simple solution for now), or have the CSS file generated based on enabled options (the preferred solution).

**Comment by mdcclxv** [comment]
What's a PR?

**Comment by Max-Github** [comment]
That would be a "Pull Request", for more details check out the following:
https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by mdcclxv** [comment]
Ok, you got it all wrong :) I'm not a coder, I'm just a user (who cares about his eyesight) suggesting a feature.

**Comment by mdcclxv** [comment]
Thank you for implementing this. But some of the images are still being inverted. See the following link:

https://subtitrari.regielive.ro/darkest-hour-30772/

**Comment by mdcclxv** [comment]
Also, if you refresh a page, the images are getting inverted for a fraction of a second, then reverted. Try in IMDB for example.

**Comment by Max-Github** [comment]
We need to add more CSS selectors to catch all the images. That image is being added by an external CSS file. I am not really sure how we can select it.

The image "uninversion" CSS is being applied at the end, so there is going to be a very short period of time where the images are going to be inverted. This is mainly noticeable on slow connections or very heavy sites.
