### ISSUE TITLE
Per Tab setting

### ISSUE THREAD

**Issue by Dxhs** [Max-Github/FireFoxInvertColors#21]
Would love to have an option to make the add-on only invert certain tabs.
For example when toggling Invert Colors, the focused tab only gets inverted, the rest stay the same.

**Comment by Max-Github** [comment]
This is going to be part of the next release.

**Comment by nicolasdanelon** [comment]
is it ready? how can I set it ? :P

**Comment by Max-Github** [comment]
This has been released a while ago. Use "alt+r" to revert colors on a single tab.
