### ISSUE TITLE
Videos in fullscreen get inverted as well

### ISSUE THREAD

**Issue by SebulonIsme** [Max-Github/FireFoxInvertColors#24]
Videos in fullscreen get inverted as well, even if pictures aren't to be inverted. (Box checked)
I'd like them not to. :-)

**Comment by Max-Github** [comment]
I just looked at youtube, and in full screen the videos are within a div and not a video tag. So it is not as simple to isolate them. 

For now you can use "Alt + R" to invert the current tab when playing that full screen video.
