### ISSUE TITLE
Port for Thunderbird

### ISSUE THREAD

**Issue by bonanza123** [Max-Github/FireFoxInvertColors#25]
Is it possible to have a port of this awesome plugin for thunderbird?

I found [these instructions](http://kb.mozillazine.org/White_on_black_-_Thunderbird) but they seem to be outdated.

**Comment by Max-Github** [comment]
Apologises for the delayed response. Have you checked out the latest release of Thunderbird (60+). There should be a built-in dark theme.

https://www.thunderbird.net/en-US/thunderbird/60.0/releasenotes/

Also what OS are you using?

**Comment by bonanza123** [comment]
Yes, it does :-), but it doesn't affect plaintext or html mails. (I'm using archlinux and opensuse tumbleweed)

**Comment by bonanza123** [comment]
FYI: On KDE there is a super easy way avoid the plugin as a whole: https://forum.kde.org/viewtopic.php?t=110152

**Comment by Max-Github** [comment]
Yes, ideally inversions would be handled by the window manager. 

This was the reason I was asking about what OS you using.
