### ISSUE TITLE
[Feature Request] List of exceptioned websites

### ISSUE THREAD

**Issue by bonanza123** [Max-Github/FireFoxInvertColors#26]
It would be great to have some kind of white / blacklisting depending on the current default mode.
E.g. lets assume my default mode is "invert colors", then I would find it quite nice if I could configure, while being on site X, that on site X, the colors should not be inverted.

**Comment by Max-Github** [comment]
The idea is to keep the plugin as simple as possible. I would recommend using the keyboard shortcuts to quickly change the current tab's colors.
