### ISSUE TITLE
Invert Colors 0.1.6 sometimes non-effective with Firefox ESR 52.9.0 and Waterfox 56.2.5

### ISSUE THREAD

**Issue by grahamperrin** [Max-Github/FireFoxInvertColors#27]
Tested at http://www.ianbicking.org/blog/2014/09/professional-transitions.html with: 

- Firefox on (Tier-3) FreeBSD-CURRENT
- Waterfox on (unsupported) FreeBSD-CURRENT. 

Version 0.1.6 of the extension seems to work with Firefox, but not with [Waterfox](http://www.waterfoxproject.org/). 

```text
$ date ; uname -v
Sat 24 Nov 2018 08:55:03 GMT
FreeBSD 13.0-CURRENT r340689 GENERIC 
$ poudriere jail -i -j current | grep -i version
Jail version:      13.0-CURRENT 1300003
Jail vcs version:  r340689
$ pkg info waterfox | grep -i repository
        repository     : poudriere
$ pkg info firefox | grep -i repository
        repository     : poudriere
$ pkg query '%o %v %R' waterfox firefox
www/waterfox 56.2.5 poudriere
www/firefox 63.0.3_3,1 poudriere
$ 
```

### Comparison

[Monochromer](https://addons.mozilla.org/addon/monochromer/) by @xia-sava is effective with Waterfox 56.2.5, so I imagine that Invert Colors could be enhanced to support Waterfox.

**Comment by Max-Github** [comment]
Waterfox is not a supported platform, I do not have time to maintain support for multiple browsers.

You are welcome to fork and maintain an add-on for waterfox.

**Comment by grahamperrin** [comment]
Thanks, from <https://addons.mozilla.org/addon/invert-colors/reviews/1241170/>: 

> … do not really know why you would expect it to be supported.

Not necessarily _supported_, but logically I did expect it to work because version 0.1.6

>> Works with … Firefox 42.0 and later 

– and Waterfox 56.0 was based on Firefox 56.0.2. 

----

Testing now with (outdated) Firefox ESR 52.9.0 on (outdated) Mac OS X 10.9.5, current version 0.1.6 of the extension is _sporadically_ effective. Sometimes does work at a page, sometimes does **not** work at the same URL. 

My first impression with Waterfox was that the extension was simply not effective but now, I find it similarly _sporadically_ effective. For example: 

![2018-11-24 23 34 29 waterfox](https://user-images.githubusercontent.com/192271/48973875-a6fdee00-f041-11e8-8265-445bf6d02212.png)

I'll add some detail from the Firefox environment …

**Comment by grahamperrin** [comment]
Re: https://github.com/Max-Github/FireFoxInvertColors/issues/28#issuecomment-441406126 now avoiding the page action …

----

With a less heavily extended Waterfox profile, the browser action (toolbar button) was, loosely speaking: 

1. consistently, repeatedly effective at https://www.waterfoxproject.org/en-US/
2. not immediately effective at e.g. https://github.com/padenot/up-to-eleven#readme – need to reload for inversion (or reversion) to take effect
3. not effective at e.g. https://addons.mozilla.org/en-GB/firefox/addon/up-to-eleven/ – expected, given Mozilla's CSP
4. then **no longer** consistently effective at https://www.waterfoxproject.org/en-US/ – as with the GitHub example, it became necessary to reload. 

I wondered whether restarting the browser would restore effectiveness for the https://www.waterfoxproject.org/en-US/ example, it did not. 

In the browser console, when the browser action is not _immediately_ effective: 

`TypeError: browser.sessions.setTabValue is not a function` `background.js:18:5` 

> `    browser.sessions.setTabValue(tabId, "invertColors", state).then(nullFunc(), nullFunc());`

– and: 

`Error: Missing host permission for the tab`

**Comment by Max-Github** [comment]
It looks like this API is not provided with Waterfox.

**Comment by Max-Github** [comment]
You might want to try version 0.1.4

**Comment by grahamperrin** [comment]
Sorry for the late reply (catching up with things after a few weeks without a proper computer). 

Yep, 0.1.4 seems fine, so far. Installed a couple of hours ago. 

Examples https://github.com/vector-im/riot-web/issues/7578#issuecomment-458006639 and below: 

![image](https://user-images.githubusercontent.com/192271/51817612-60d43d80-22c3-11e9-90bf-56e8e96b1d6c.png)

– combined with [ReFont](https://addons.mozilla.org/addon/refont/). 

https://addons.mozilla.org/addon/invert-colors/versions/ appears correct: 

![image](https://user-images.githubusercontent.com/192271/51817859-81e95e00-22c4-11e9-8c65-1253444961f4.png)

Thanks!
