### ISSUE TITLE
Invert Colors 0.1.6 page action (address bar button) not effective with Firefox ESR 52.9.0

### ISSUE THREAD

**Issue by grahamperrin** [Max-Github/FireFoxInvertColors#28]
Tested at https://blog.mozilla.org/firefox/ on Mac OS X 10.9.5. 

As far as I can tell, this issue is: 

- consistently reproducible with the outdated ESR
- not reproducible with the current ESR 60.3.0.

**Comment by Max-Github** [comment]
OK, so support needs to be dropped for the old ESR. 

I will re-upload and update the compatibility list.

**Comment by grahamperrin** [comment]
OK, incidentally the browser action (toolbar button) usually does work.
