### ISSUE TITLE
Hue rotation

### ISSUE THREAD

**Issue by yusf** [Max-Github/FireFoxInvertColors#29]
If the CSS `filter: hue-rotate(180deg);` is used when inversion is active colors will retain their original values to a closer degree.

Thanks for a simple yet super useful addon.

**Comment by Max-Github** [comment]
Thank you for the tip. I will test this out.

**Comment by yusf** [comment]
Great! See https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/hue-rotate

**Comment by Max-Github** [comment]
It does look good. 

I have to now think about it a little. As I want to avoid adding extra configurations if I can avoid it. And I do not want to change the defaults for current users. But I do like it.

**Comment by yusf** [comment]
Just make it opt-in?

**Comment by Max-Github** [comment]
That is what I am considering, but it is an extra option. 

One of the goals is to have the least amount of configuration options, so everything should work out of the box.

**Comment by yusf** [comment]
But there seem to be serious performance issue with applying the filter globally, at least for me. 😰

**Comment by Max-Github** [comment]
Which filter is causing a performance issue.

**Comment by Max-Github** [comment]
It seem to require hardware acceleration to work properly, which will basically cause batteries to drain. Might have to give it a miss.
