### ISSUE TITLE
global alt-shift-r broken?

### ISSUE THREAD

**Issue by dsshulman** [Max-Github/FireFoxInvertColors#32]
Global inversion is broken for me -- alt+shift+r has no effect. Alt+R still works for individual tabs.

Firefox 72.0 (64-bit)
Microsoft Windows 10 Pro 10.0.18362 Build 18362
Dell Inc. Latitude 7280

**Comment by ericjmcalvin** [comment]
The problem also exists on Firefox 72.0+ for Linux (it worked fine through 71.x).  The button on the toolbar for global inversion also does not work.  If you right click on it, and select invert colors, it works but not apply it globally (once the URL changes by clicking a link or reloading the page it reverts back to OFF).  Hopefully Max is still maintaining this project :)

**Comment by Max-Github** [comment]
I will look into this shortly.

**Comment by ehb54** [comment]
Thanks ericjmcalvin for the "If you right click on it, and select invert colors, it works but not apply it globally"
Gives me a work-around until this is fixed.

**Comment by ehb54** [comment]
Note - the current "broken" nature is quite painful in Google docs. It does not keep the tab inverted, but occasionally during typing resets to normal colors.
