### ISSUE TITLE
feature request: save list of domains to invert / exclude

### ISSUE THREAD

**Issue by chinwobble** [Max-Github/FireFoxInvertColors#34]
Some websites already have good dark themes and don't need to be inverted like youtube, docs.microsoft.com, etc.

Can we have a whitelist so we don't invert every single website?

**Comment by Jeanuel** [comment]
Thank you for the module which works very well.

In addition, some poorly programmed sites are not readable when inverted. It'd be great to have a white list !

**Comment by Max-Github** [comment]
This is supported on a domain level. It is possible to exclude domains from inversions.
