### ISSUE TITLE
Did not see color inverted on firefox locally 

### ISSUE THREAD

**Issue by Jimmyzz2** [Max-Github/FireFoxInvertColors#36]
Hi, I am not be able to see color inverted. When I ran command `web-ext run -s src/`, a new firefox window opened and I tried different sites like facebook, reddit and github on the new window, however no changes in color that I have noticed. I am running firefox version 4.2.0(latest) and firefox 76.0.1(latest). Any help will be appreciated!

**Comment by Max-Github** [comment]
Did you trigger the colour inversion?

**Comment by Jimmyzz2** [comment]
I did not trigger the colour inversion. I think that might be the step I missed. Can you tell me how to trigger the colour inversion?

**Comment by Max-Github** [comment]
You can press the button (top right circle) and select the option.
Or use the keyboard shortcuts: ALT+R or ALT+SHIFT+R.

I have just pushed an update (still alpha) where I have added a popup with extra details (replacing the options page), and adding a basic whitelist feature.

I will see how well this works and if I am happy with it, will cleanup the code and release it.

**Comment by Jimmyzz2** [comment]
Thanks, got to work after pressing ALT+R. 

The new update will be really helpful since I saw people want to have the whitelist feature.

**Comment by Max-Github** [comment]
Yeah, I finally had time to add it.
