### ISSUE TITLE
Seems to have stopped working on my Firefox with today's update.

### ISSUE THREAD

**Issue by ftrader** [Max-Github/FireFoxInvertColors#6]
45.9 ESR

**Comment by Max-Github** [comment]
The extension/add-on has been updated to conform to the WebExtensions format. I think Support for WebExtensions started with FF 48. 

If you are using a version of FF that does not support WebExtensions, then you will need to stay with the previous version.

**Comment by ftrader** [comment]
Thanks, I'll close this issue, and thanks for your explanation.
