### ISSUE TITLE
Allow for only inverting the current tab

### ISSUE THREAD

**Issue by jronallo** [Max-Github/FireFoxInvertColors#9]
Currently all tabs of all windows have their colors inverted. It would be nice to allow for only the current tab having its colors inverted. Even better would be a preference to either invert colors of just the current tab in the current window, all tabs in the current window, or all tabs in all windows.

**Comment by Max-Github** [comment]
The general idea is to keep this as simple as possible. 

You can always use [alt]+[shift]+r to quickly invert the colors. 

The simplest solution would be to have a drop down on the preferences page with the such options:

-Global
-Invert Current Windows.
-Invert Current Tab.

You are welcome to add this.
